import { useState, useEffect } from 'react';
import {
  collection,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  query,
  where,
} from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Clause } from '../types';

const MOCK_CLAUSES: Record<string, Clause[]> = {
  'mock-1': [
    {
      id: 'clause-m1-1',
      projectId: 'mock-1',
      title: 'Tax Credit Transfer Mechanics',
      content: 'Seller shall transfer all eligible Investment Tax Credits (ITCs) and Production Tax Credits (PTCs) to Buyer pursuant to Section 6418 of the Internal Revenue Code.',
      probability: 0.9,
      exposure: 4000000,
      mitigation: 0.7,
      subjectiveFriction: 6.5,
      expectedValue: 1080000,
      riskLevel: 'Medium',
      clarificationQuestion: 'Has IRS pre-registration been completed for all 12 solar assets?',
      aiRationale: 'Core of the TCTA structure. Transfer must comply with IRS guidance on credit monetization.',
      attorneyNotes: 'Verify IRS registration numbers for each facility.',
      createdAt: '2024-11-15T00:00:00Z',
    },
    {
      id: 'clause-m1-2',
      projectId: 'mock-1',
      title: 'Recapture Indemnification',
      content: 'Seller shall indemnify and hold harmless Buyer from any tax credit recapture arising from a disposition or change in use within the recapture period.',
      probability: 0.3,
      exposure: 8000000,
      mitigation: 0.85,
      subjectiveFriction: 9.0,
      expectedValue: 360000,
      riskLevel: 'High',
      clarificationQuestion: 'What is the proposed escrow amount for recapture risk coverage?',
      aiRationale: 'Critical risk allocation clause. Recapture exposure can equal 100% of transferred credits.',
      attorneyNotes: 'Negotiate escrow equal to 20% of credit value for 5-year recapture period.',
      createdAt: '2024-11-15T00:00:00Z',
    },
    {
      id: 'clause-m1-3',
      projectId: 'mock-1',
      title: 'Qualifying Income Representation',
      content: 'Seller represents that all transferred credits were generated by qualifying energy property placed in service in accordance with applicable IRS guidance.',
      probability: 0.2,
      exposure: 2000000,
      mitigation: 0.9,
      subjectiveFriction: 4.0,
      expectedValue: 40000,
      riskLevel: 'Low',
      clarificationQuestion: 'Are all commissioning certificates and interconnection agreements in order?',
      aiRationale: 'Fundamental eligibility representation. Failure triggers full credit reversal.',
      attorneyNotes: '',
      createdAt: '2024-11-15T00:00:00Z',
    },
  ],
  'mock-2': [
    {
      id: 'clause-m2-1',
      projectId: 'mock-2',
      title: 'Purchase Price Adjustment',
      content: 'The Purchase Price shall be subject to a post-closing adjustment based on Final Net Working Capital compared to a Target NWC of $12,500,000.',
      probability: 0.75,
      exposure: 5000000,
      mitigation: 0.6,
      subjectiveFriction: 7.5,
      expectedValue: 1500000,
      riskLevel: 'Medium',
      clarificationQuestion: 'What accounting standards apply to the NWC calculation?',
      aiRationale: 'Standard M&A protection mechanism. Prevents value leakage between signing and closing.',
      attorneyNotes: 'Buyer insists on GAAP-consistent calculation methodology.',
      createdAt: '2024-10-20T00:00:00Z',
    },
    {
      id: 'clause-m2-2',
      projectId: 'mock-2',
      title: 'Indemnification Cap',
      content: "Seller's aggregate indemnification liability shall not exceed 15% of the Purchase Price ($18,000,000) except for Fundamental Representations which shall be capped at 100%.",
      probability: 0.45,
      exposure: 18000000,
      mitigation: 0.8,
      subjectiveFriction: 8.5,
      expectedValue: 1620000,
      riskLevel: 'High',
      clarificationQuestion: 'Which representations qualify as Fundamental?',
      aiRationale: 'Market-standard indemnification structure. 15% cap balances seller and buyer risk.',
      attorneyNotes: 'R&W insurance obtained for $50M coverage.',
      createdAt: '2024-10-20T00:00:00Z',
    },
  ],
};

const isFirebaseConfigured = () => {
  return !!(
    import.meta.env.VITE_FIREBASE_API_KEY &&
    import.meta.env.VITE_FIREBASE_PROJECT_ID
  );
};

export function useClauses(projectId?: string) {
  const [clauses, setClauses] = useState<Clause[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (projectId) {
      loadClauses(projectId);
    } else {
      setClauses([]);
    }
  }, [projectId]);

  async function loadClauses(pid: string) {
    setLoading(true);
    if (!isFirebaseConfigured()) {
      setClauses(MOCK_CLAUSES[pid] || []);
      setLoading(false);
      return;
    }
    try {
      const q = query(collection(db, 'clauses'), where('projectId', '==', pid));
      const snapshot = await getDocs(q);
      const data = snapshot.docs.map((d) => ({ id: d.id, ...d.data() } as Clause));
      setClauses(data.length > 0 ? data : MOCK_CLAUSES[pid] || []);
    } catch (e) {
      console.error(e);
      setError('Failed to load clauses');
      setClauses(MOCK_CLAUSES[pid] || []);
    } finally {
      setLoading(false);
    }
  }

  async function addClause(clause: Omit<Clause, 'id'>) {
    if (!isFirebaseConfigured()) {
      const newClause = { ...clause, id: `local-clause-${Date.now()}` };
      setClauses((prev) => [...prev, newClause]);
      return newClause;
    }
    try {
      const docRef = await addDoc(collection(db, 'clauses'), clause);
      const newClause = { ...clause, id: docRef.id };
      setClauses((prev) => [...prev, newClause]);
      return newClause;
    } catch (e) {
      console.error(e);
      setError('Failed to add clause');
    }
  }

  async function updateClause(id: string, updates: Partial<Clause>) {
    if (!isFirebaseConfigured()) {
      setClauses((prev) => prev.map((c) => (c.id === id ? { ...c, ...updates } : c)));
      return;
    }
    try {
      await updateDoc(doc(db, 'clauses', id), updates);
      setClauses((prev) => prev.map((c) => (c.id === id ? { ...c, ...updates } : c)));
    } catch (e) {
      console.error(e);
      setError('Failed to update clause');
    }
  }

  async function deleteClause(id: string) {
    if (!isFirebaseConfigured()) {
      setClauses((prev) => prev.filter((c) => c.id !== id));
      return;
    }
    try {
      await deleteDoc(doc(db, 'clauses', id));
      setClauses((prev) => prev.filter((c) => c.id !== id));
    } catch (e) {
      console.error(e);
      setError('Failed to delete clause');
    }
  }

  return { clauses, loading, error, addClause, updateClause, deleteClause, setClauses };
}
